# Check NEORV32 software framework and test processor using cpu_test program

name: 'Test Toolchains'

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - releases/*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: 'Test Toolchains'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: '💾 Checkout'
        uses: actions/checkout@v2

      # Setup system env variables
      - name: '▶️ Check Toolchains'
        run: /bin/bash -c "chmod u+x $GITHUB_WORKSPACE/test.sh && $GITHUB_WORKSPACE/test.sh"
