name: 'Test Toolchains'
 
on:
  push:
  workflow_dispatch:

  build:
    runs-on: ubuntu-latest
    name: 'Test Toolchains'

    steps:

      - name: '💾 Checkout'
        uses: actions/checkout@v2

      - name: '▶️ Check Toolchains'
        run: /bin/bash -c "chmod u+x $GITHUB_WORKSPACE/test.sh && $GITHUB_WORKSPACE/test.sh"
